[data]
num_nodes = 1024
lag = 4
horizon = 4
val_ratio = 0.2
test_ratio = 0.2
normalizer = std
column_wise = False

[model]
input_dim = 1
output_dim = 1
embed_dim = 20
embed_d_model = 32
rnn_units = 64
num_layers = 2
cheb_order = 2
weight_decay = 1e-3
lamb = 0.05
k=2

[train]
loss_func = mae
seed = 42
batch_size = 32
epochs = 200
lr_init = 0.001
lr_decay = False
lr_decay_rate = 0.5
lr_decay_step = 12,30
early_stop = True
early_stop_patience = 15
grad_norm = False
max_grad_norm = 5
real_value = True

[test]
mae_thresh = None
mape_thresh = 0.

[log]
log_step = 20
plot = False